# =============================================================================
#  Unit Tests on Various Go Versions
# =============================================================================
# This Workflow runs unit tests on various Go versions over Docker on any push.
# This action caches the built Docker image for a month unless any changes in
# the Dockerfile or go.mod were made.
name: Various Go Version Tests

on:
  workflow_dispatch:
  push:

jobs:
  go:
    name: Run tests on various Go versions via container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build Docker images if no-exists
        run: |
          : # Pull images one-by-one for stability
          docker pull golang:1.24-alpine
          docker pull golang:alpine
          : # Build container images
          docker compose --file ./.github/docker-compose.yml build

      - name: Run tests on minimum supported Go version
        run: docker compose --file ./.github/docker-compose.yml run min

      - name: Run tests on latest Go
        run: docker compose --file ./.github/docker-compose.yml run latest
